services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./registry:/usr/share/nginx/html:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      default:
        aliases:
          - example.com

  alpine:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    command:
      - curl
      - -s
      - https://example.com
    networks:
      - default
    depends_on:
      - nginx

networks:
  default:
