FROM hashicorp/terraform:1.9.4

# Copy the self-signed certificate from the build context and add it to the trusted store
COPY certs/server.crt /usr/local/share/ca-certificates/server.crt

# Update the trusted certificates
RUN update-ca-certificates
