FROM alpine:3.21.3

# Copy the self-signed certificate from the build context and add it to the trusted store
COPY certs/server.crt /usr/local/share/ca-certificates/server.crt

# Install curl and other tools, and then update the trusted certificates
RUN apk add --no-cache curl ca-certificates openssl gpg gpg-agent bash zip jq go \
    && update-ca-certificates
