services:
  nginx:
    image: nginx:1.27.4-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./registry:/usr/share/nginx/html:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      default:
        aliases:
          - example.com

  alpine:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    command:
      - curl
      - -s
      - https://example.com
    volumes:
      - .:/workspace
    working_dir: /workspace
    networks:
      - default
    # depends_on:
    #   - nginx

networks:
  default:
